import { InitiativeObject, SpellObject, SessionData } from "./initiative";
import { CollectionTypes } from "./Enums";

export enum EmitTypes {
  GET_INITIAL = "GET_INITIAL",
  GET_SPELLS = "GET_SPELLS",
  NEXT = "NEXT",
  PREVIOUS = "PREVIOUS",
  ROUND_START = "ROUND_START",
  UPDATE_ALL_INITIATIVE = "UPDATE_ALL_INITIATIVE",
  DELETE_ONE_INITIATIVE = "DELETE_ONE_INITIATIVE",
  DELETE_ALL_INITIATIVE = "DELETE_ALL_INITIATIVE",
  CREATE_NEW_INITIATIVE = "CREATE_NEW_INITIATIVE",
  UPDATE_ITEM_INITIATIVE = "UPDATE_ITEM_INITIATIVE",
  UPDATE_RECORD_INITIATIVE = "UPDATE_RECORD_INITIATIVE",
  UPDATE_ALL_SPELL = "UPDATE_ALL_SPELL",
  DELETE_ONE_SPELL = "DELETE_ONE_SPELL",
  DELETE_ALL_SPELL = "DELETE_ALL_SPELL",
  CREATE_NEW_SPELL = "CREATE_NEW_SPELL",
  UPDATE_ITEM_SPELL = "UPDATE_ITEM_SPELL",
  UPDATE_RECORD_SPELL = "UPDATE_RECORD_SPELL",
  UPDATE_SESSION = "UPDATE_SESSION",
  RE_ROLL = "RE_ROLL",
  RESORT = "RESORT",
  DISCORD = "DISCORD",
} //socket.emit(EmitType)

export enum SessionFunctionTypes {
  GET_INITIAL_INIT = "GET_INITIAL_INIT",
  GET_INITIAL_SPELLS = "GET_INITIAL_SPELLS",
  NEXT = "NEXT",
  PREVIOUS = "PREVIOUS",
  ROUND_START = "ROUND_START",
  EDIT = "EDIT",
  DELETE_DATA = "DELETE_DATA",
  CREATE_NEW = "CREATE_NEW",
  RE_ROLL = "RE_ROLL",
  UPDATE_ALL = "UPDATE_ALL",
  DISCORD = "DISCORD",
  REMOVE_STATUS_EFFECT = "REMOVE_STATUS_EFFECT",
  SET_CURRENT_TURN = "SET_CURRENT_TURN",
}

export interface SocketData {
  payload:
    | InitiativeObject
    | InitiativeObject[]
    | SpellObject
    | SpellObject[]
    | SessionData;
  sessionId: string;
  collectionType: CollectionTypes;
  docId?: string;
}
